server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  datasource:
    username: abhi
    password: abhi
    url: jdbc:mysql://localhost:3306/microservice
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: configserver:http://localhost:8084

#  profiles:
#    active: dev

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelBreaker:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      ratingHotelBreaker:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
