server:
  port: 8083
spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**


        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/staff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rate/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#okta config for api gateway
okta:
  oauth2:
    issuer: https://dev-05514227.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaaeag3uv5ETQ4ZG5d7
    client-secret: PMiSljr3X3602acTnlu0tl9U53ecTbJWA1apTLTk
    scopes: openid, profile, email, offline_access